package edu.ipcmax.core.loader;

import edu.ipcmax.core.function.PiecewiseConstFn;
import edu.ipcmax.core.function.PiecewiseLinearFn;
import edu.ipcmax.core.graph.Edge;
import edu.ipcmax.core.graph.Node;
import edu.ipcmax.core.graph.TDGraph;
import edu.ipcmax.core.validate.GraphValidator;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.zip.GZIPInputStream;

/**
 * Loader for the synthetic graph files generated by {@code generate_td_graph.py}.
 */
public final class GeneratedGraphLoader {
    private static final Pattern NUMBER_PATTERN = Pattern.compile("-?\\d+(?:\\.\\d+)?(?:[eE][+-]?\\d+)?");

    /**
     * Loads a generated graph directory.
     */
    public GeneratedGraphDataset load(Path directory) throws IOException {
        Objects.requireNonNull(directory, "directory");
        if (!Files.isDirectory(directory)) {
            throw new IOException("generated graph directory does not exist: " + directory);
        }

        ManifestSummary manifest = readManifest(directory.resolve("manifest.json"));
        Map<Integer, Node> nodes = readNodes(directory.resolve("nodes.csv.gz"));
        List<EdgeBuilder> builders = readStaticEdges(directory.resolve("edges_static.csv.gz"));
        readTravelTimeFunctions(directory.resolve("travel_time_functions.jsonl.gz"), builders);
        readScoreFunctions(directory.resolve("score_functions.jsonl.gz"), builders);

        List<Edge> edges = new ArrayList<>(builders.size());
        for (EdgeBuilder builder : builders) {
            if (builder.travelTimeFunction == null) {
                throw new IOException("missing travel-time function for arc_id " + builder.arcId);
            }
            if (builder.scoreFunction == null) {
                builder.scoreFunction = PiecewiseConstFn.zeroFullDay();
            }
            edges.add(builder.toEdge());
        }

        TDGraph graph = new TDGraph(nodes.values(), edges);
        GraphValidator.validate(graph, false);

        if (manifest != null) {
            if (manifest.numNodes() != graph.nodeCount()) {
                throw new IOException("manifest node count mismatch: manifest=" + manifest.numNodes()
                        + " loaded=" + graph.nodeCount());
            }
            if (manifest.numArcs() != graph.edgeCount()) {
                throw new IOException("manifest arc count mismatch: manifest=" + manifest.numArcs()
                        + " loaded=" + graph.edgeCount());
            }
        }

        return new GeneratedGraphDataset(graph, manifest, directory);
    }

    private static Map<Integer, Node> readNodes(Path path) throws IOException {
        Map<Integer, Node> nodes = new HashMap<>();
        try (BufferedReader reader = openMaybeGzip(path)) {
            String header = reader.readLine();
            if (!"node_id,x,y".equals(header)) {
                throw new IOException(path + ": invalid nodes header");
            }

            String line;
            long lineNumber = 1;
            while ((line = reader.readLine()) != null) {
                lineNumber++;
                if (line.isBlank()) {
                    continue;
                }
                String[] parts = line.split(",", -1);
                if (parts.length != 3) {
                    throw new IOException(path + ":" + lineNumber + ": invalid node row");
                }
                int id = parseInt(parts[0], path, lineNumber, "node_id");
                long x = parseLong(parts[1], path, lineNumber, "x");
                long y = parseLong(parts[2], path, lineNumber, "y");
                if (nodes.put(id, new Node(id, x, y)) != null) {
                    throw new IOException(path + ":" + lineNumber + ": duplicate node id " + id);
                }
            }
        }
        return nodes;
    }

    private static List<EdgeBuilder> readStaticEdges(Path path) throws IOException {
        List<EdgeBuilder> edges = new ArrayList<>();
        try (BufferedReader reader = openMaybeGzip(path)) {
            String header = reader.readLine();
            if (!"arc_id,u,v,distance,base_travel_time".equals(header)) {
                throw new IOException(path + ": invalid static edge header");
            }

            String line;
            long lineNumber = 1;
            while ((line = reader.readLine()) != null) {
                lineNumber++;
                if (line.isBlank()) {
                    continue;
                }
                String[] parts = line.split(",", -1);
                if (parts.length != 5) {
                    throw new IOException(path + ":" + lineNumber + ": invalid static edge row");
                }
                int arcId = parseInt(parts[0], path, lineNumber, "arc_id");
                if (arcId != edges.size()) {
                    throw new IOException(path + ":" + lineNumber + ": expected arc_id " + edges.size()
                            + " but found " + arcId);
                }
                EdgeBuilder builder = new EdgeBuilder();
                builder.arcId = arcId;
                builder.u = parseInt(parts[1], path, lineNumber, "u");
                builder.v = parseInt(parts[2], path, lineNumber, "v");
                builder.distance = parseLong(parts[3], path, lineNumber, "distance");
                builder.baseTravelTime = parseDouble(parts[4], path, lineNumber, "base_travel_time");
                edges.add(builder);
            }
        }
        return edges;
    }

    private static void readTravelTimeFunctions(Path path, List<EdgeBuilder> builders) throws IOException {
        try (BufferedReader reader = openMaybeGzip(path)) {
            String line;
            long lineNumber = 0;
            while ((line = reader.readLine()) != null) {
                lineNumber++;
                if (line.isBlank()) {
                    continue;
                }
                int arcId = intJsonField(line, "arc_id", path, lineNumber);
                EdgeBuilder builder = builderFor(builders, arcId, path, lineNumber);
                validateJsonEndpoint(line, builder, path, lineNumber);
                String array = jsonArrayField(line, "travel_time_breakpoints", path, lineNumber);
                builder.travelTimeFunction = new PiecewiseLinearFn(parseBreakpoints(array, path, lineNumber));
            }
        }
    }

    private static void readScoreFunctions(Path path, List<EdgeBuilder> builders) throws IOException {
        if (!Files.exists(path)) {
            return;
        }
        try (BufferedReader reader = openMaybeGzip(path)) {
            String line;
            long lineNumber = 0;
            while ((line = reader.readLine()) != null) {
                lineNumber++;
                if (line.isBlank()) {
                    continue;
                }
                int arcId = intJsonField(line, "arc_id", path, lineNumber);
                EdgeBuilder builder = builderFor(builders, arcId, path, lineNumber);
                validateJsonEndpoint(line, builder, path, lineNumber);
                String array = jsonArrayField(line, "score_intervals", path, lineNumber);
                builder.scoreFunction = new PiecewiseConstFn(parseScoreIntervals(array, path, lineNumber));
            }
        }
    }

    private static ManifestSummary readManifest(Path path) throws IOException {
        if (!Files.exists(path)) {
            return null;
        }
        String text = Files.readString(path, StandardCharsets.UTF_8);
        return new ManifestSummary(
                intJsonField(text, "num_nodes", path, 1),
                intJsonField(text, "num_arcs", path, 1),
                longJsonField(text, "seed", path, 1),
                intJsonField(text, "selected_score_edge_count", path, 1),
                booleanJsonField(text, "unlisted_edges_have_score_zero", path, 1));
    }

    private static BufferedReader openMaybeGzip(Path path) throws IOException {
        InputStream input = Files.newInputStream(path);
        if (path.getFileName().toString().endsWith(".gz")) {
            input = new GZIPInputStream(input);
        }
        return new BufferedReader(new InputStreamReader(input, StandardCharsets.UTF_8));
    }

    private static EdgeBuilder builderFor(List<EdgeBuilder> builders, int arcId, Path path, long lineNumber)
            throws IOException {
        if (arcId < 0 || arcId >= builders.size()) {
            throw new IOException(path + ":" + lineNumber + ": unknown arc_id " + arcId);
        }
        return builders.get(arcId);
    }

    private static void validateJsonEndpoint(String line, EdgeBuilder builder, Path path, long lineNumber)
            throws IOException {
        int u = intJsonField(line, "u", path, lineNumber);
        int v = intJsonField(line, "v", path, lineNumber);
        if (u != builder.u || v != builder.v) {
            throw new IOException(path + ":" + lineNumber + ": endpoint mismatch for arc_id " + builder.arcId);
        }
    }

    private static List<PiecewiseLinearFn.Breakpoint> parseBreakpoints(String array, Path path, long lineNumber)
            throws IOException {
        List<Double> numbers = numbers(array);
        if (numbers.size() % 2 != 0) {
            throw new IOException(path + ":" + lineNumber + ": breakpoint array must contain pairs");
        }
        List<PiecewiseLinearFn.Breakpoint> breakpoints = new ArrayList<>();
        for (int i = 0; i < numbers.size(); i += 2) {
            breakpoints.add(new PiecewiseLinearFn.Breakpoint(numbers.get(i), numbers.get(i + 1)));
        }
        return breakpoints;
    }

    private static List<PiecewiseConstFn.Interval> parseScoreIntervals(String array, Path path, long lineNumber)
            throws IOException {
        List<Double> numbers = numbers(array);
        if (numbers.size() % 3 != 0) {
            throw new IOException(path + ":" + lineNumber + ": score interval array must contain triples");
        }
        List<PiecewiseConstFn.Interval> intervals = new ArrayList<>();
        for (int i = 0; i < numbers.size(); i += 3) {
            double scoreNumber = numbers.get(i + 2);
            int score = (int) scoreNumber;
            if (score != scoreNumber) {
                throw new IOException(path + ":" + lineNumber + ": score must be an integer");
            }
            intervals.add(new PiecewiseConstFn.Interval(numbers.get(i), numbers.get(i + 1), score));
        }
        return intervals;
    }

    private static List<Double> numbers(String text) {
        Matcher matcher = NUMBER_PATTERN.matcher(text);
        List<Double> numbers = new ArrayList<>();
        while (matcher.find()) {
            numbers.add(Double.parseDouble(matcher.group()));
        }
        return numbers;
    }

    private static String jsonArrayField(String text, String field, Path path, long lineNumber) throws IOException {
        int key = text.indexOf("\"" + field + "\"");
        if (key < 0) {
            throw new IOException(path + ":" + lineNumber + ": missing JSON field " + field);
        }
        int start = text.indexOf('[', key);
        if (start < 0) {
            throw new IOException(path + ":" + lineNumber + ": missing array for JSON field " + field);
        }
        int depth = 0;
        for (int index = start; index < text.length(); index++) {
            char ch = text.charAt(index);
            if (ch == '[') {
                depth++;
            } else if (ch == ']') {
                depth--;
                if (depth == 0) {
                    return text.substring(start, index + 1);
                }
            }
        }
        throw new IOException(path + ":" + lineNumber + ": unterminated array for JSON field " + field);
    }

    private static int intJsonField(String text, String field, Path path, long lineNumber) throws IOException {
        long value = longJsonField(text, field, path, lineNumber);
        if (value < Integer.MIN_VALUE || value > Integer.MAX_VALUE) {
            throw new IOException(path + ":" + lineNumber + ": integer field out of range: " + field);
        }
        return (int) value;
    }

    private static long longJsonField(String text, String field, Path path, long lineNumber) throws IOException {
        Pattern pattern = Pattern.compile("\"" + Pattern.quote(field) + "\"\\s*:\\s*(-?\\d+)");
        Matcher matcher = pattern.matcher(text);
        if (!matcher.find()) {
            throw new IOException(path + ":" + lineNumber + ": missing integer JSON field " + field);
        }
        return Long.parseLong(matcher.group(1));
    }

    private static boolean booleanJsonField(String text, String field, Path path, long lineNumber) throws IOException {
        Pattern pattern = Pattern.compile("\"" + Pattern.quote(field) + "\"\\s*:\\s*(true|false)");
        Matcher matcher = pattern.matcher(text);
        if (!matcher.find()) {
            throw new IOException(path + ":" + lineNumber + ": missing boolean JSON field " + field);
        }
        return Boolean.parseBoolean(matcher.group(1));
    }

    private static int parseInt(String text, Path path, long lineNumber, String field) throws IOException {
        try {
            return Integer.parseInt(text);
        } catch (NumberFormatException ex) {
            throw new IOException(path + ":" + lineNumber + ": invalid integer " + field + ": " + text, ex);
        }
    }

    private static long parseLong(String text, Path path, long lineNumber, String field) throws IOException {
        try {
            return Long.parseLong(text);
        } catch (NumberFormatException ex) {
            throw new IOException(path + ":" + lineNumber + ": invalid long " + field + ": " + text, ex);
        }
    }

    private static double parseDouble(String text, Path path, long lineNumber, String field) throws IOException {
        try {
            return Double.parseDouble(text);
        } catch (NumberFormatException ex) {
            throw new IOException(path + ":" + lineNumber + ": invalid decimal " + field + ": " + text, ex);
        }
    }

    private static final class EdgeBuilder {
        private int arcId;
        private int u;
        private int v;
        private long distance;
        private double baseTravelTime;
        private PiecewiseLinearFn travelTimeFunction;
        private PiecewiseConstFn scoreFunction;

        private Edge toEdge() {
            return new Edge(arcId, u, v, distance, baseTravelTime, travelTimeFunction, scoreFunction);
        }
    }
}
